# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicreader', '0002_auto_20161027_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicdatabase',
            name='fileup',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
